live_config_reload = true

[colors.bright]
black = "0x6e7681"
blue = "0x79c0ff"
cyan = "0x56d4dd"
green = "0x56d364"
magenta = "0xd2a8ff"
red = "0xffa198"
white = "0xf0f6fc"
yellow = "0xe3b341"

[colors.cursor]
cursor = "0xe6edf3"
text = "0x30363d"

[colors.normal]
black = "0x484f58"
blue = "0x58a6ff"
cyan = "0x39c5cf"
green = "0x3fb950"
magenta = "0xbc8cff"
red = "0xff7b72"
white = "0xb1bac4"
yellow = "0xd29922"

[colors.primary]
background = "#121212"
foreground = "#ffffff"

[cursor]
blink_interval = 550
blink_timeout = 30

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 9.0

[font.normal]
family = "Monaco"
style = "Regular"

[scrolling]
multiplier = 3

[selection]
save_to_clipboard = true

[window]
opacity = 0.99
startup_mode = "Maximized"
title = " "
