alias t='tmux'
alias v='vim'
alias o='open .'
alias n='neofetch'
alias m='make'
alias p='python'
alias le='less'
alias cl='clear'

alias gc='git commit -m'
alias ga='git add'
alias gaa='git add -A'
alias gs='git status'
alias gl='git log'
alias gd='git diff'
alias gh='git log > /tmp/history && vim /tmp/history'
alias vgh='vim /tmp/history'

alias hg='history | grep'
alias h='history'
alias l='ls -lAh'

alias mkdir='mkdir -pv'
